// <auto-generated />
using System;
using Agenda.Infrastructure.Context.SQLServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agenda.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Agenda.Core.Entities.Core.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("EndDate");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("EventType");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Location");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("StartDate");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 2,
                            Description = "Reunión semanal del equipo de desarrollo",
                            EndDate = new DateTime(2026, 3, 25, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Shared",
                            Location = "Sala A",
                            StartDate = new DateTime(2026, 3, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Reunión de equipo"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 2,
                            Description = "Revisión del avance del proyecto IATEC",
                            EndDate = new DateTime(2026, 3, 26, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Exclusive",
                            Location = "Sala B",
                            StartDate = new DateTime(2026, 3, 26, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Revisión de proyecto"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 3,
                            Description = "Capacitación en nuevas tecnologías",
                            EndDate = new DateTime(2026, 3, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Shared",
                            Location = "Auditorio",
                            StartDate = new DateTime(2026, 3, 27, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Capacitación"
                        });
                });

            modelBuilder.Entity("Agenda.Core.Entities.Core.EventInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("EventId");

                    b.Property<int>("InvitedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("InvitedByUserId");

                    b.Property<int>("InvitedUserId")
                        .HasColumnType("int")
                        .HasColumnName("InvitedUserId");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("RespondedAt");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("SentAt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("EventInvitations", (string)null);
                });

            modelBuilder.Entity("Agenda.Core.Entities.Core.EventParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("EventId");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("EventParticipants", (string)null);
                });

            modelBuilder.Entity("Agenda.Core.Entities.Core.UserEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("EventId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("Status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserEvents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1,
                            Status = "Active",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            EventId = 2,
                            Status = "Active",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            EventId = 3,
                            Status = "Active",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Agenda.Core.Entities.Core.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@agenda.com",
                            Name = "Admin",
                            Password = "admin123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "luis@agenda.com",
                            Name = "Luis García",
                            Password = "luis123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "maria@agenda.com",
                            Name = "María López",
                            Password = "maria123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
